before_install:
  - sudo apt-get update
  - sudo apt-get install cmake

compiler:
  - gcc

language: c

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake ..
  - make
  - ./bin/test_cutils

